### ISSUE TITLE
Layer error: Array.reshape: Shape incompatible with array's existing dimensions.

### ISSUE THREAD

**Issue by tedescodanilo** [wouellette/ee-dynamic-time-warping#4]
Dear William Ouellette,

I am trying to adapt the code for my dataset and I am getting the following error:

DTW classification: Layer error: Array.reshape: Shape incompatible with array's existing dimensions: [-1, 8, 6] vs. [268, 40].

DTW dissimilarity score: Layer error: Array.reshape: Shape incompatible with array's existing dimensions: [-1, 8, 6] vs. [268, 40].

I am a beginner in google earth engine, could you help me find where I am going wrong?

**Comment by RossDF** [comment]
Hey tedescodanilo,

I've received a similar error when my TIMESERIES_LEN/PATTERNS_LEN (from the example code) didn't match the number of images in my time-series

**Comment by wouellette** [comment]
Hi Tedescodanilo,

Could you share the script you are working with so I can help troubleshoot? 

Regards
