### ISSUE TITLE
Memory Limits exceeded

### ISSUE THREAD

**Issue by RossDF** [wouellette/ee-dynamic-time-warping#5]
Hey,

I'm trying to implement this library for dtw and am encountering memory issues within GEE.
Are there any hard limits in terms of the amount of images in the time-series, or number of sample points, number of labels, or overall region size that you are aware of?

Just as a test I'm trying to export dtw_class and the task does run for a long while

Everything before this step is fine, however the output from this function can't be printed or exported.
`var dtw_min_dist = function(key, val){
  key = ee.Number.parse(key);
  // Function to format the signatures to a DTW-ready EE array
  var training_data_list = DTW.prepareSignatures(reference_signatures,
                                                 CLASS_NAME,
                                                 key,
                                                 BAND_NO,
                                                 PATTERNS_LEN,
                                                 band_names);

  // Compute the class-wise DTW distance
  return ee.ImageCollection(DTW.DTWDist(training_data_list,
                                        s2_input_asset.select("d_0_NDVI"),
                                        {patterns_no: val,
                                        band_no: BAND_NO,
                                        timeseries_len: TIMESERIES_LEN,
                                        patterns_len: PATTERNS_LEN,
                                        constraint_type: 'time-weighted',
                                        distance_type: 'angular',
                                        beta: BETA,
                                        alpha: ALPHA
                                        })
         ).min()
         .rename('dtw')
         // Add class band corresponding to the land cover/crop class computed.
         // This is useful/necessary to generate the hard classification map from the dissimilarity values
         .addBands(ee.Image(key).toByte().rename('band'));
};`

For the variables:
`// Input data parameters
var CLASS_NAME = 'labelno';
var AGG_INTERVAL = 5;
var TIMESERIES_LEN = 37;
var PATTERNS_LEN = 37;
var CLASS_NO = 6;
var S2_BAND_LIST = ["d_0_NDVI"];
var BAND_NO = S2_BAND_LIST.length; 
var DOY_BAND = 'doy';
`
Where the number of number of signatures is 331
AOI size is ~3700 km2

**Comment by wouellette** [comment]
Can you share your code so it can be reproduced? I suspect you can still export it as an asset or to cloud storage, but cannot print it real time.
